(()=>{
  const v='6.4.35-payment-policy-engine-1';
    const postJobV='6.4.42-post-job-experience-1';
  const fieldOpsV='6.4.41-staff-operations-v3-1';
  const receiptV='6.4.45-payment-receipts-1';
  const analyticsV='6.4.67-profile-validation-1';
  const supabaseVersion='2.117.1';
  document.write(`<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@${supabaseVersion}"><\/script>`);
  document.write(`<script src="/account-original.js?v=${analyticsV}"><\/script>`);
  document.write(`<script src="/account-captcha-guard.js?v=${v}"><\/script>`);
  document.write(`<script src="/account-mfa-guard.js?v=6.4.71-auth-client-ready-1"><\/script>`);
  document.write(`<script src="/account-security-email.js?v=${v}"><\/script>`);
  document.write(`<script src="/account-service-availability.js?v=${v}"><\/script>`);
  document.write(`<script src="/account-payments.js?v=${receiptV}"><\/script>`);
  document.write(`<script src="/account-booking-journey.js?v=${v}"><\/script>`);
  document.write(`<script src="/account-booking-policy.js?v=${analyticsV}"><\/script>`);
  document.write(`<script src="/account-privacy-center.js?v=${v}"><\/script>`);
  document.write(`<link rel="stylesheet" href="/account-post-job.css?v=${postJobV}">`);
  document.write(`<script src="/account-post-job.js?v=${postJobV}"><\/script>`);
  document.write(`<script src="/account-field-eta.js?v=${fieldOpsV}"><\/script>`);
})();
