(()=>{
  const v='6.4.30-security-hardening-1';
  document.write(`<link rel="stylesheet" href="/admin-inbox-safety.css?v=${v}">`);
  document.write(`<script src="/privileged-login-captcha.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-original.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-mfa-guard.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-security-hardening.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-inbox-safety.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-address-harvest.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-services.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-booking-operations.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-post-job-followup.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-payment-settings.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-window-performance.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-business-finance.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-business-finance-polish.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-finance-receipts.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-system-health.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-newsletter-center.js?v=${v}"><\/script>`);
})();
