(()=>{
  const v='6.4.37-admin-website-crash-fix-1';
  const modalLayoutV='6.4.38-admin-wide-modal-fix-1';
  const roleV='6.4.39-access-roles-1';
  const fieldOpsV='6.4.41-staff-operations-v3-1';
  const reviewV='6.4.43-google-reviews-1';
  const paymentV='6.4.44-stripe-live-readiness-1';
  const receiptV='6.4.45-payment-receipts-1';
  const inboxV='6.4.48-inbox-workflow-polish-fix-1';
  const analyticsV='6.4.57-analytics-load-lifecycle-1';
  const financeFxV='6.4.59-finance-receipt-stability-1';
  const financeReceiptV='6.4.59-finance-receipt-stability-1';
  document.write(`<link rel="stylesheet" href="/admin-inbox-safety.css?v=${v}">`);
  document.write(`<link rel="stylesheet" href="/admin-page-analytics.css?v=${analyticsV}">`);
  document.write(`<link rel="stylesheet" href="/admin-modal-layout.css?v=${modalLayoutV}">`);
  document.write(`<link rel="stylesheet" href="/admin-field-incidents.css?v=${fieldOpsV}">`);
  document.write(`<link rel="stylesheet" href="/admin-review-dashboard.css?v=${reviewV}">`);
  document.write(`<script src="/privileged-login-captcha.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-original.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-brand-assets.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-mfa-guard.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-security-hardening.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-role-management.js?v=${roleV}"><\/script>`);
  document.write(`<script src="/admin-inbox-safety.js?v=${inboxV}"><\/script>`);
  document.write(`<script src="/admin-page-analytics.js?v=${analyticsV}"><\/script>`);
  document.write(`<script src="/admin-address-harvest.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-services.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-booking-operations.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-field-incidents.js?v=${fieldOpsV}"><\/script>`);
  document.write(`<script src="/admin-post-job-followup.js?v=${reviewV}"><\/script>`);
  document.write(`<script src="/admin-payment-settings.js?v=${paymentV}"><\/script>`);
  document.write(`<script src="/admin-payment-receipts.js?v=${receiptV}"><\/script>`);
  document.write(`<script src="/admin-window-performance.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-business-finance.js?v=${financeFxV}"><\/script>`);
  document.write(`<script src="/admin-business-finance-polish.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-finance-receipts.js?v=${financeReceiptV}"><\/script>`);
  document.write(`<script src="/admin-system-health.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-newsletter-center.js?v=${v}"><\/script>`);
  document.write(`<script src="/admin-privacy-center.js?v=${v}"><\/script>`);
})();
