const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function initMobileNav(){const header=document.querySelector('.site-header'),btn=document.querySelector('.mobile-menu');if(!header||!btn)return;const close=()=>{header.classList.remove('nav-open');btn.setAttribute('aria-expanded','false');btn.textContent='☰'};btn.onclick=()=>{const open=!header.classList.contains('nav-open');header.classList.toggle('nav-open',open);btn.setAttribute('aria-expanded',String(open));btn.textContent=open?'×':'☰'};header.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
const fields={
  windows:`<div class="field-row"><label>Number of exterior windows<input id="units" type="number" min="1" max="5000" value="12"></label><label>Window type<select id="detail"><option value="1">Standard windows</option><option value="1.15">Large / bay windows</option><option value="1.28">Mixed / difficult windows</option></select></label></div>`,
  gutters:`<div class="field-row"><label>Approx. gutter length (metres)<input id="units" type="number" min="1" max="5000" value="25"></label><label>Condition<select id="detail"><option value="1">Normal build-up</option><option value="1.18">Heavy debris</option><option value="1.3">Plants / blocked downpipes</option></select></label></div>`,
  roof:`<div class="field-row"><label>Approx. roof area (m²)<input id="units" type="number" min="1" max="5000" value="55"></label><label>Roof condition<select id="detail"><option value="1">Light clean</option><option value="1.2">Moss / staining</option><option value="1.38">Heavy moss / steep pitch</option></select></label></div>`,
  jetwash:`<div class="field-row"><label>Area to wash (m²)<input id="units" type="number" min="1" max="5000" value="35"></label><label>Surface<select id="detail"><option value="1">Patio / paving</option><option value="1.08">Driveway</option><option value="1.18">Walls / mixed surfaces</option></select></label></div>`,
  handyman:`<div class="field-row"><label>Estimated work time (hours)<input id="units" type="number" min="1" max="24" value="2"></label><label>Complexity<select id="detail"><option value="1">Simple job</option><option value="1.2">Moderate</option><option value="1.4">Specialist / multiple tasks</option></select></label></div>`,
  tour3d:`<div class="field-row"><label>Property floor area (m²)<input id="units" type="number" min="20" max="5000" value="110"></label><label>Package<select id="detail"><option value="1">3D walkthrough</option><option value="1.18">3D + floor plan</option><option value="1.35">Agent package + priority delivery</option></select></label></div>`
};
let sb=null,config={stripeEnabled:false,depositPercent:20,adsEnabled:false},latestQuote=null,latestBooking=null,currentProfile=null,currentSession=null,publicSettings={},publicMap=null,chatCaptchaToken='',siteAdvertisingEnabled=true,selectedQuoteAddress=null;
let chatState={sessionId:localStorage.getItem('namdar_chat_session')||'',guestToken:localStorage.getItem('namdar_chat_token')||'',pollTimer:null};
const serviceNames={windows:'Windows',gutters:'Gutters',roof:'Roof',jetwash:'Jet wash',handyman:'Handyman',tour3d:'3D tour'};
function selectedService(){return document.querySelector('input[name="service"]:checked')?.value||'windows'}
function renderFields(){$('#dynamicFields').innerHTML=fields[selectedService()]}
function formatGBP(n){return Math.round(Number(n)||0).toLocaleString('en-GB')}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeUrl(v=''){try{const u=new URL(String(v||''),location.origin);return u.protocol==='https:'||u.origin===location.origin?u.href:''}catch{return''}}
async function api(path,options={}){const session=sb?(await sb.auth.getSession()).data.session:null;const headers={'Content-Type':'application/json',...(options.headers||{})};if(session?.access_token)headers.Authorization=`Bearer ${session.access_token}`;const r=await fetch(path,{...options,headers});const data=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function setBusy(btn,busy,label){if(!btn)return;if(busy){btn.dataset.label=btn.textContent;btn.textContent=label||'Please wait…';btn.disabled=true}else{btn.textContent=btn.dataset.label||btn.textContent;btn.disabled=false}}
function localSlot(date,time){const[start,end]=time.split('|');return{startsAt:new Date(`${date}T${start}:00`).toISOString(),endsAt:new Date(`${date}T${end}:00`).toISOString()}}
function bookingDateMinimum(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)}
function prepareBookingUi(){const f=$('#bookingDate');if(f){const min=bookingDateMinimum();f.min=min;if(!f.value||f.value<min){const d=new Date();d.setDate(d.getDate()+1);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());f.value=d.toISOString().slice(0,10)}}const intro=$('#bookingIntro');if(intro)intro.textContent=config.stripeEnabled?'Choose a preferred slot. Namdar will confirm availability and the final price by email. A secure deposit option will appear when your booking is ready.':'Choose a preferred slot. Namdar will confirm availability and the final price by email — no payment is taken at this stage.'}
function applyBrand(settings){const brand=settings.brand||{};const name=brand.name||'Namdar';$$('[data-brand-name]').forEach(x=>x.textContent=name.toUpperCase());$$('[data-brand-mark]').forEach(x=>{if(brand.logo_url){x.innerHTML=`<img src="${esc(brand.logo_url)}" alt="${esc(name)} logo">`;x.classList.add('brand-mark-image')}else{x.textContent=brand.logo_text||'N';x.classList.remove('brand-mark-image')}});if($('#publicSupportEmail'))$('#publicSupportEmail').textContent=brand.support_email||brand.business_email||'support@namdar.co.uk';const contact=settings.contact||{};if($('#publicPhone'))$('#publicPhone').textContent=contact.phone?`☎ ${contact.phone}`:'☎ Business phone coming soon';if($('#publicArea'))$('#publicArea').textContent=`⌖ ${contact.service_area_text||'London and surrounding areas'}`;if($('#contactIntro')&&contact.ticket_intro)$('#contactIntro').textContent=contact.ticket_intro}
function applyAppearance(settings){const a=settings.appearance||{};const theme=a.theme||'auto';document.documentElement.dataset.theme=theme;document.body.classList.toggle('christmas-theme',a.seasonal==='christmas'||a.christmas_enabled===true);const m=settings.maintenance||{};if(m.enabled){$('#maintenanceOverlay')?.classList.remove('hidden');$('#maintenanceMessage').textContent=m.message||'We are improving the Namdar website. Please check back shortly.'}else $('#maintenanceOverlay')?.classList.add('hidden');siteAdvertisingEnabled=(settings.advertising||{}).enabled!==false&&(settings.advertising||{}).home_slot_enabled!==false}
function renderServiceMap(areas){const box=$('#publicServiceMap');if(!box)return;if(!window.L){box.innerHTML='<p>Coverage map is loading…</p>';return}if(publicMap){publicMap.remove();publicMap=null}const valid=(areas||[]).filter(a=>{if((a.coverage_mode==='administrative'||a.coverage_mode==='polygon')&&a.geojson)return true;const lat=Number(a.latitude),lng=Number(a.longitude),r=Number(a.radius_km||0);return Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180&&Number.isFinite(r)&&r>0});if(!valid.length){box.innerHTML='<div class="map-empty">Service coverage will appear here as Namdar adds operating areas.</div>';$('#serviceAreaList').innerHTML='';return}publicMap=L.map(box,{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(publicMap);const bounds=L.latLngBounds([]);for(const a of valid){const ll=[Number(a.latitude),Number(a.longitude)];let layer=null;if((a.coverage_mode==='administrative'||a.coverage_mode==='polygon')&&a.geojson){try{layer=L.geoJSON(a.geojson).addTo(publicMap).bindPopup(esc(a.label));const b=layer.getBounds();if(b.isValid())bounds.extend(b)}catch{layer=null}}if(!layer&&Number.isFinite(ll[0])&&Number.isFinite(ll[1])){layer=L.circle(ll,{radius:Number(a.radius_km||5)*1000}).addTo(publicMap).bindPopup(esc(a.label));bounds.extend(layer.getBounds())}if(Number.isFinite(ll[0])&&Number.isFinite(ll[1]))bounds.extend(ll)}if(bounds.isValid())publicMap.fitBounds(bounds,{padding:[35,35],maxZoom:11});$('#serviceAreaList').innerHTML=valid.map(a=>{const services=(a.service_keys||[]).length?(a.service_keys||[]).map(k=>serviceNames[k]||k).join(', '):'All services';return `<span>${esc(a.label)} · ${a.coverage_mode==='administrative'?`${(a.admin_area_codes||[]).length} selected council${(a.admin_area_codes||[]).length===1?'':'s'}`:a.coverage_mode==='polygon'?'precise boundary':`${Number(a.radius_km||0)} km radius`} · ${esc(services)}</span>`}).join('')}

async function loadPublicData(){try{const r=await fetch('/api/public-data'),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load content');publicSettings=d.settings||{};applyBrand(publicSettings);applyAppearance(publicSettings);renderServiceMap(d.serviceAreas||[]);$('#chatPresence').textContent=d.liveStaffOnline?'A Namdar team member is online':(config.aiEnabled?'AI assistant · team can reply by ticket':'Namdar assistant · team can reply by ticket');if(d.offers?.length){$('#offerTitle').textContent=d.offers[0].title;$('#offerText').textContent=d.offers[0].body||''}const jobs=d.jobs||[];if(jobs.length){$('#work')?.classList.remove('hidden');$('#jobGallery').innerHTML=jobs.map((j,i)=>{const image=Array.isArray(j.image_urls)?j.image_urls[0]:null;return `<article class="job-card">${image?`<div class="job-image real-image" style="background-image:url('${esc(image)}')"><span>${esc(j.location_label||serviceNames[j.service_key]||'Namdar job')}</span></div>`:`<div class="job-image" style="filter:hue-rotate(${i*18}deg)"><span>${esc(j.location_label||serviceNames[j.service_key]||'Namdar job')}</span></div>`}<div class="job-body"><h3><a href="/work/${encodeURIComponent(j.id)}">${esc(j.title)}</a></h3><p>${esc(j.description||'Completed by Namdar.')}</p>${j.tour_url?`<p><a class="text-link" href="${esc(safeUrl(j.tour_url))}" target="_blank" rel="noopener">Open 3D tour →</a></p>`:''}</div></article>`}).join('')}else renderFallbackJobs();if(localStorage.getItem('namdar_cookie_choice')==='marketing')enableAds()}catch(e){console.error(e);renderFallbackJobs()}}
function renderFallbackJobs(){const section=$('#work');if(section)section.classList.add('hidden');const gallery=$('#jobGallery');if(gallery)gallery.innerHTML=''}
async function initSupabase(){const r=await fetch('/api/config');const c=await r.json();if(!r.ok||!c.ok)throw new Error(c.error||'Could not load site configuration.');config=c;if(!window.supabase?.createClient)throw new Error('Supabase client library did not load.');sb=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);sb.auth.onAuthStateChange(()=>refreshAccountState());await refreshAccountState();initTurnstile();initAdsConsent()}
async function refreshAccountState(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();currentSession=session;const link=$('#accountTopLink');if(link)link.textContent=session?'My account':'Customer login';$('#adminTopLink')?.classList.add('hidden');$('#savedDetailsNotice')?.classList.add('hidden');$('#quoteDetailsFields')?.classList.remove('hidden');currentProfile=null;if(!session)return;const {data:profile}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();currentProfile=profile||{};if(profile){$('#quoteName').value=profile.full_name||'';$('#quoteEmail').value=session.user.email||'';$('#quotePhone').value=profile.phone||'';$('#postcode').value=profile.postcode||'';if(profile.property_type&&$('#propertyType'))$('#propertyType').value=profile.property_type;$('#savedDetailsNotice')?.classList.remove('hidden');if(profile.full_name&&profile.phone&&profile.postcode)$('#quoteDetailsFields')?.classList.add('hidden');if(['admin','staff'].includes(profile.role))$('#adminTopLink')?.classList.remove('hidden');if($('#newsletterName'))$('#newsletterName').value=profile.full_name||'';if($('#newsletterEmail'))$('#newsletterEmail').value=session.user.email||'';if($('#contactName'))$('#contactName').value=profile.full_name||'';if($('#contactEmail'))$('#contactEmail').value=session.user.email||'';if($('#chatName'))$('#chatName').value=profile.full_name||'';if($('#chatEmail'))$('#chatEmail').value=session.user.email||''}}
function initTurnstile(){if(!config.turnstileSiteKey)return;const render=()=>{if(!window.turnstile)return setTimeout(render,200);const el=$('#chatTurnstile');if(!el||el.dataset.rendered)return;el.classList.remove('hidden');window.turnstile.render('#chatTurnstile',{sitekey:config.turnstileSiteKey,callback:t=>chatCaptchaToken=t,'expired-callback':()=>chatCaptchaToken='' });el.dataset.rendered='1'};render()}
function showQuote(q){$('#estimateNumber').textContent=formatGBP(q.estimate);const discounts=[];if(q.promo)discounts.push(`${q.promo.code}: −£${Number(q.promo.discount).toFixed(2)}`);if(q.reward)discounts.push(`Reward ${q.reward.code}: −£${Number(q.reward.discount).toFixed(2)}`);$('#discountStatus').textContent=discounts.length?`Applied: ${discounts.join(' · ')}`:'No discount code applied.';$('#estimateRange').textContent=q.manualReview?`Guide range £${formatGBP(q.min)}–£${formatGBP(q.max)}. The details suggest a manual access/complexity review.`:`Guide range £${formatGBP(q.min)}–£${formatGBP(q.max)} before final review.`;$('#bookEstimate').disabled=false}
async function uploadQuotePhotos(quoteId,files){
  if(!currentSession||!files?.length)return 0;if(files.length>8)throw new Error('Please choose no more than 8 quote photos.');
  const paths=[];for(const file of files){if(!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))throw new Error(`${file.name} is not a supported image.`);if(file.size>8*1024*1024)throw new Error(`${file.name} is larger than 8 MB.`);const safe=(file.name||'photo.jpg').replace(/[^a-zA-Z0-9._-]/g,'-'),path=`${currentSession.user.id}/quotes/${quoteId}/request/${Date.now()}-${Math.random().toString(36).slice(2)}-${safe}`;const {error}=await sb.storage.from('customer-project-files').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;paths.push(path)}
  try{await api('/api/customer-quote-action',{method:'POST',body:JSON.stringify({action:'add_photos',quoteId,paths})})}catch(e){await sb.storage.from('customer-project-files').remove(paths).catch(()=>null);throw e}return paths.length;
}
async function trackView(){if(window.NamdarAnalytics?.trackView)return window.NamdarAnalytics.trackView();try{let host='';try{host=document.referrer?new URL(document.referrer).hostname:''}catch{}await fetch('/api/track-view',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:location.pathname,referrer:host})})}catch{}}
async function checkStripeReturn(){const p=new URLSearchParams(location.search),sid=p.get('session_id');if(p.get('payment')==='success'&&sid){try{const d=await api(`/api/payment-status?session_id=${encodeURIComponent(sid)}`,{method:'GET'});alert(d.paid?'Payment confirmed. Thank you — your Namdar booking has been updated.':'Stripe returned, but the payment is not marked paid yet.');history.replaceState({},'',location.pathname+location.hash)}catch(e){console.error(e)}}}
function initAdsConsent(){const choice=localStorage.getItem('namdar_cookie_choice');if(!choice){$('#cookieBanner')?.classList.remove('hidden');return}if(choice==='marketing')enableAds()}
function enableAds(){if(!siteAdvertisingEnabled||!config.adsEnabled||!config.adsenseClient||!config.adsenseSlotHome)return;const sec=$('#adSection');if(!sec)return;sec.classList.remove('hidden');if(!document.querySelector('script[data-namdar-adsense]')){const sc=document.createElement('script');sc.async=true;sc.dataset.namdarAdsense='1';sc.crossOrigin='anonymous';sc.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(config.adsenseClient)}`;document.head.appendChild(sc)}const slot=$('#adsenseHomeSlot');slot.innerHTML=`<ins class="adsbygoogle" style="display:block" data-ad-client="${esc(config.adsenseClient)}" data-ad-slot="${esc(config.adsenseSlotHome)}" data-ad-format="auto" data-full-width-responsive="true"></ins>`;setTimeout(()=>{try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch{}},500)}
function appendChat(role,message){const el=$('#chatMessages');if(!el)return;const b=document.createElement('div');b.className=`chat-bubble ${role}`;b.textContent=message;el.appendChild(b);el.scrollTop=el.scrollHeight}
function rememberChat(session){if(!session)return;chatState.sessionId=session.id||chatState.sessionId;chatState.guestToken=session.guestToken||chatState.guestToken;if(chatState.sessionId)localStorage.setItem('namdar_chat_session',chatState.sessionId);if(chatState.guestToken)localStorage.setItem('namdar_chat_token',chatState.guestToken)}
async function pollChat(){if(!chatState.sessionId)return;try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({action:'poll',sessionId:chatState.sessionId,guestToken:chatState.guestToken})});rememberChat(d.session);const el=$('#chatMessages');const current=el.dataset.lastCount||'0';if(Number(current)!==(d.messages||[]).length){el.innerHTML=(d.messages||[]).map(m=>`<div class="chat-bubble ${esc(m.sender_role==='staff'?'staff':m.sender_role)}">${esc(m.message)}</div>`).join('');el.dataset.lastCount=String((d.messages||[]).length);el.scrollTop=el.scrollHeight}}catch(e){console.debug('chat poll',e.message)}}
function startChatPolling(){clearInterval(chatState.pollTimer);chatState.pollTimer=setInterval(pollChat,5000);pollChat()}

initMobileNav();const requestedService=new URLSearchParams(location.search).get('service');if(requestedService&&serviceNames[requestedService]){const requestedRadio=document.querySelector(`input[name="service"][value="${requestedService}"]`);if(requestedRadio)requestedRadio.checked=true}renderFields();loadPublicData();trackView();initSupabase().then(()=>{prepareBookingUi();return checkStripeReturn()}).catch(e=>{console.error(e);$('#quoteStatus').textContent='Database connection error. Check /api/health and Vercel environment variables.'});
$$('input[name="service"]').forEach(x=>x.addEventListener('change',()=>{renderFields();const p=$('#postcode');if(p?.value.trim())verifyQuotePostcode()}));$$('[data-service-link]').forEach(a=>a.addEventListener('click',()=>{const r=document.querySelector(`input[name="service"][value="${a.dataset.serviceLink}"]`);if(r){r.checked=true;renderFields()}}));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));$$('a[href="/account?tab=tickets"]').forEach(a=>a.setAttribute('href','/account?tab=support'));
async function loadQuoteAddressChoices(postcode){const wrap=$('#quoteAddressChoiceWrap'),select=$('#quoteAddressChoice');if(!wrap||!select)return 0;const d=await api(`/api/address-search?postcode=${encodeURIComponent(postcode)}`);select.innerHTML='<option value="">Choose an address…</option>'+((d.addresses||[]).map(a=>`<option value="${esc(a.id)}">${esc(a.address)}</option>`).join(''));wrap.classList.toggle('hidden',!(d.addresses||[]).length);return (d.addresses||[]).length}
async function chooseQuoteAddress(id){selectedQuoteAddress=null;if(!id)return;const d=await api(`/api/address-get?id=${encodeURIComponent(id)}`);selectedQuoteAddress=d.address||null}
async function verifyQuotePostcode(){const field=$('#postcode'),status=$('#quotePostcodeStatus'),service=selectedService();if(!field?.value.trim()){if(status)status.textContent='Enter a postcode first.';return false}if(status)status.textContent='Checking postcode and service availability…';try{const p=await api(`/api/postcode?postcode=${encodeURIComponent(field.value.trim())}&service=${encodeURIComponent(service)}`);field.value=p.postcode;const loc=[p.region||p.city,p.district].filter(Boolean).join(' · '),coverage=p.coverage||{},cover=coverage.configured?(coverage.covered?` · ✓ ${serviceNames[service]} available${p.area?.label?` via ${p.area.label}`:''}`:` · × ${serviceNames[service]} not currently covered`):' · coverage plan not configured yet';const count=await loadQuoteAddressChoices(p.postcode);if(status)status.textContent=`✓ Postcode verified${loc?' · '+loc:''}${cover}${count?` · ${count} address${count===1?'':'es'} available`:''}`;field.dataset.verified='true';field.dataset.covered=coverage.configured?String(!!coverage.covered):'unconfigured';if(coverage.configured)window.NamdarAnalytics?.track?.('postcode_checked',{postcode:p.postcode,covered:!!coverage.covered});return true}catch(e){field.dataset.verified='false';delete field.dataset.covered;if(status)status.textContent=e.message;return false}}
$('#quoteVerifyPostcode')?.addEventListener('click',verifyQuotePostcode);$('#quoteAddressChoice')?.addEventListener('change',e=>chooseQuoteAddress(e.target.value).catch(err=>{selectedQuoteAddress=null;$('#quotePostcodeStatus').textContent=err.message}));$('#postcode')?.addEventListener('input',()=>{selectedQuoteAddress=null;if($('#postcode'))$('#postcode').dataset.verified='false';if($('#quotePostcodeStatus'))$('#quotePostcodeStatus').textContent='';$('#quoteAddressChoiceWrap')?.classList.add('hidden') });
$('#quoteForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#quoteSubmit');$('#quoteStatus').textContent='';setBusy(btn,true,'Calculating…');try{const files=[...($('#quotePhotos')?.files||[])];if(files.length>8)throw new Error('Please choose no more than 8 quote photos.');const d=await api('/api/quote',{method:'POST',body:JSON.stringify({customerName:$('#quoteName').value,email:$('#quoteEmail').value,phone:$('#quotePhone').value,postcode:$('#postcode').value,serviceKey:selectedService(),visitorId:window.NamdarAnalytics?.sessionId||undefined,promoCode:$('#promoCode').value.trim(),rewardCode:$('#rewardCode').value.trim(),inputs:{units:Number($('#units').value),detail:Number($('#detail').value),extra:Number($('#extra').value),floors:Number($('#storeys').value),access:$('#access').value,urgency:$('#urgency').value,propertyType:$('#propertyType').value,frequency:$('#frequency').value,notes:$('#quoteNotes').value}})});latestQuote=d.quote;window.NamdarAnalytics?.track?.('quote_submitted',{quoteId:d.quote?.id||undefined});let uploaded=0;if(files.length&&currentSession){setBusy(btn,true,'Uploading photos…');uploaded=await uploadQuotePhotos(d.quote.id,files)}showQuote(d.quote);const photoMsg=uploaded?` · ${uploaded} private photo${uploaded===1?'':'s'} attached`:files.length&&!currentSession?' · Sign in to My Namdar with this email to add your photos':'';$('#quoteStatus').textContent=`Saved. Quote reference: ${d.quote.id}`+(config.emailEnabled?' · Confirmation emailed.':'')+photoMsg+(d.quote.manualReview?' — manual review recommended.':'')}catch(err){$('#quoteStatus').textContent=err.message}finally{setBusy(btn,false)}});
$('#bookEstimate').addEventListener('click',()=>{if(latestQuote)location.href=`/account?tab=quotes&quote=${encodeURIComponent(latestQuote.id)}`});
$('#bookingForm').addEventListener('submit',async e=>{e.preventDefault();if(!latestQuote)return;const btn=$('#bookingSubmit');setBusy(btn,true,'Saving slot…');try{const slot=localSlot($('#bookingDate').value,$('#bookingTime').value);const d=await api('/api/booking',{method:'POST',body:JSON.stringify({quoteId:latestQuote.id,address:$('#bookingAddress').value,...slot})});latestBooking=d.booking;window.NamdarAnalytics?.track?.('booking_submitted',{quoteId:latestQuote?.id||undefined,bookingId:d.booking?.id||undefined});const el=$('#bookingStatus');el.style.display='block';el.textContent=config.emailEnabled?'Booking request saved. We have also emailed you a confirmation. Namdar will confirm the slot and final price shortly.':'Booking request saved. Namdar will confirm the slot and final price shortly.';if(config.stripeEnabled&&d.booking?.status==='confirmed'){$('#payBooking').textContent=`Pay ${config.depositPercent}% booking deposit`;$('#payBooking').classList.remove('hidden')}}catch(err){const el=$('#bookingStatus');el.style.display='block';el.textContent=err.message}finally{setBusy(btn,false)}});
$('#payBooking').addEventListener('click',async()=>{if(!latestBooking)return;const btn=$('#payBooking');setBusy(btn,true,'Opening secure payment…');try{const d=await api('/api/create-checkout',{method:'POST',body:JSON.stringify({bookingId:latestBooking.id})});location.href=d.url}catch(e){alert(e.message);setBusy(btn,false)}});
$('#newsletterForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#newsletterSubmit');setBusy(btn,true,'Joining…');try{await api('/api/newsletter-subscribe',{method:'POST',body:JSON.stringify({email:$('#newsletterEmail').value.trim(),fullName:$('#newsletterName').value.trim(),source:'homepage'})});$('#newsletterStatus').textContent='Subscribed. Watch your inbox for Namdar offers and news.';e.target.reset()}catch(err){$('#newsletterStatus').textContent=err.message}finally{setBusy(btn,false)}});
$('#chatLauncher').onclick=()=>{$('#chatWidget').classList.remove('hidden');startChatPolling()};$('#chatClose').onclick=()=>{$('#chatWidget').classList.add('hidden');clearInterval(chatState.pollTimer)};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),message=input.value.trim();if(!message)return;appendChat('customer',message);input.value='';try{const d=await api('/api/chat',{method:'POST',body:JSON.stringify({action:'message',sessionId:chatState.sessionId,guestToken:chatState.guestToken,name:$('#chatName').value.trim(),email:$('#chatEmail').value.trim(),message,turnstileToken:chatCaptchaToken})});rememberChat(d.session);if(d.reply)appendChat('assistant',d.reply);if(d.staffOnline&&d.session?.mode==='human')$('#chatPresence').textContent='Namdar team member online';startChatPolling()}catch(err){appendChat('assistant',`Sorry — ${err.message}`)}};
$('#chatTicket').onclick=()=>{location.href='/account?tab=support'};
$('#essentialOnly')?.addEventListener('click',()=>{localStorage.setItem('namdar_cookie_choice','essential');$('#cookieBanner').classList.add('hidden')});$('#allowMarketing')?.addEventListener('click',()=>{localStorage.setItem('namdar_cookie_choice','marketing');$('#cookieBanner').classList.add('hidden');enableAds()});
