const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const token=new URLSearchParams(location.search).get('token')||'';let selectedRating=0,reviewUrl='';
const ratingWords={1:'Very poor',2:'Poor',3:'Okay',4:'Good',5:'Excellent'};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setRating(n){selectedRating=Number(n)||0;$$('[data-rating]').forEach(b=>{const on=Number(b.dataset.rating)<=selectedRating;b.classList.toggle('selected',on);b.setAttribute('aria-checked',Number(b.dataset.rating)===selectedRating?'true':'false')});$('#ratingLabel').textContent=selectedRating?`${selectedRating}/5 · ${ratingWords[selectedRating]}`:'Choose 1–5 stars'}
function jobLine(job){const d=job?.completedAt?new Date(job.completedAt).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}):'';return `<strong>${esc(job?.service||'Namdar service')}</strong>${d?` · ${esc(d)}`:''}${job?.address?`<br><small>${esc(job.address)}</small>`:''}`}
function renderResult(status,rating,url=''){$('#feedbackForm').classList.add('hidden');$('#feedbackLoading').classList.add('hidden');const positive=status==='positive';reviewUrl=url||'';$('#feedbackResult').classList.remove('hidden');$('#feedbackResult').innerHTML=positive?`<div class="feedback-result-icon">✓</div><h2>Thank you — we're glad it went well.</h2><p>Your ${rating}/5 rating has been saved.</p>${reviewUrl?'<p>If you have another minute, a public review would really help a local business like Namdar.</p><button id="publicReviewBtn" class="primary-btn full" type="button">Leave a public review</button>':''}<a class="ghost-btn full" href="/account">Back to My Namdar</a>`:`<div class="feedback-result-icon support">♥</div><h2>Thank you for telling us privately.</h2><p>Your ${rating}/5 feedback has been sent directly to the Namdar support team. It is not being posted publicly by us.</p><p>We'll review what happened and follow up if anything needs attention.</p><a class="primary-btn full" href="/account">Open My Namdar</a>`;const btn=$('#publicReviewBtn');if(btn)btn.onclick=publicReview}
async function publicReview(){const btn=$('#publicReviewBtn');if(!reviewUrl)return;btn.disabled=true;btn.textContent='Opening review…';try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'public_review_click'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not open review link.');{const u=(()=>{try{const x=new URL(d.url);return x.protocol==='https:'?x.href:''}catch{return''}})();if(!u)throw new Error('Review link is invalid.');location.href=u}}catch(e){btn.disabled=false;btn.textContent='Leave a public review';alert(e.message)}}
async function init(){if(!token){$('#feedbackLoading').textContent='This feedback link is missing or invalid.';return}try{const r=await fetch(`/api/feedback?token=${encodeURIComponent(token)}`),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load feedback.');$('#feedbackIntro').innerHTML=`Hi ${esc(String(d.job.customerName||'there').split(' ')[0])}, thanks for choosing Namdar.<br>${jobLine(d.job)}`;$('#feedbackLoading').classList.add('hidden');if(d.feedback.submitted){renderResult(d.feedback.status,d.feedback.rating,d.reviewUrl);return}$('#feedbackForm').classList.remove('hidden')}catch(e){$('#feedbackLoading').textContent=e.message}}
$$('[data-rating]').forEach(b=>b.onclick=()=>setRating(b.dataset.rating));
$('#feedbackForm').onsubmit=async e=>{e.preventDefault();if(!selectedRating){$('#feedbackStatus').textContent='Please choose a rating from 1 to 5.';return}const btn=$('#submitFeedback');btn.disabled=true;btn.textContent='Sending…';$('#feedbackStatus').textContent='';try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,rating:selectedRating,comments:$('#feedbackComments').value.trim()})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save feedback.');renderResult(d.status,d.rating,d.reviewUrl)}catch(err){$('#feedbackStatus').textContent=err.message;btn.disabled=false;btn.textContent='Send feedback'}};
init();
