const VERSION='namdar-staff-v6.4.41-staff-operations-v3-1';
const STATIC_CACHE=`${VERSION}-static`;
const RUNTIME_CACHE=`${VERSION}-runtime`;
const LOCAL_ASSETS=['/staff','/staff.html','/staff.js','/staff-original.js','/staff-experience-v2.js','/staff-experience-v2.css','/staff-operations-v3.js','/staff-operations-v3.css','/staff-auth-readiness.js','/privileged-login-captcha.js','/staff-mfa-guard.js','/staff-closeout.js','/styles.css','/staff.webmanifest','/staff-icon-180.png','/staff-icon-192.png','/staff-icon-512.png'];
const AUTH_CRITICAL=new Set(['/staff.js','/staff-original.js','/staff-auth-readiness.js','/privileged-login-captcha.js','/staff-mfa-guard.js']);
const REMOTE_ASSETS=['https://unpkg.com/leaflet@1.9.4/dist/leaflet.css','https://unpkg.com/leaflet@1.9.4/dist/leaflet.js','https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.116.0'];
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(STATIC_CACHE);await cache.addAll(LOCAL_ASSETS);await Promise.allSettled(REMOTE_ASSETS.map(async url=>{try{const r=await fetch(url,{mode:'cors',cache:'no-store'});if(r.ok)await cache.put(url,r.clone())}catch{}}));await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith('namdar-staff-')&&!n.startsWith(VERSION)).map(n=>caches.delete(n)));await self.clients.claim()})())});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin===location.origin&&url.pathname.startsWith('/api/'))return;if(url.hostname.endsWith('.supabase.co'))return;if(url.hostname.includes('tile.openstreetmap.org'))return;
  if(req.mode==='navigate'&&(url.pathname==='/staff'||url.pathname==='/staff.html')){event.respondWith((async()=>{try{const fresh=await fetch(req,{cache:'no-store'});const cache=await caches.open(STATIC_CACHE);await cache.put('/staff',fresh.clone());return fresh}catch{return (await caches.match('/staff'))||(await caches.match('/staff.html'))}})());return}
  const local=url.origin===location.origin&&LOCAL_ASSETS.some(p=>url.pathname===new URL(p,location.origin).pathname);
  const remote=REMOTE_ASSETS.includes(url.href);
  if(local&&AUTH_CRITICAL.has(url.pathname)){event.respondWith((async()=>{try{const fresh=await fetch(req,{cache:'no-store'});if(fresh.ok){const cache=await caches.open(STATIC_CACHE);await cache.put(url.pathname,fresh.clone())}return fresh}catch{return (await caches.match(req))||(await caches.match(url.pathname))||new Response('Offline',{status:503,headers:{'Content-Type':'text/plain'}})}})());return}
  if(local||remote){event.respondWith((async()=>{const cached=await caches.match(req)||await caches.match(url.pathname)||await caches.match(url.href);if(cached){fetch(req).then(async fresh=>{if(fresh.ok){const cache=await caches.open(local?STATIC_CACHE:RUNTIME_CACHE);await cache.put(local?url.pathname:req,fresh.clone())}}).catch(()=>{});return cached}try{const fresh=await fetch(req);if(fresh.ok){const cache=await caches.open(local?STATIC_CACHE:RUNTIME_CACHE);await cache.put(local?url.pathname:req,fresh.clone())}return fresh}catch{return new Response('Offline',{status:503,headers:{'Content-Type':'text/plain'}})}})())}
});
