const q=new URLSearchParams(location.search),token=q.get('token')||'',statusEl=document.getElementById('unsubscribeStatus'),form=document.getElementById('newsletterPreferenceForm');
const endpoint=()=>'/api/newsletter-unsubscribe?token='+encodeURIComponent(token);
async function request(options={}){const r=await fetch(endpoint(),{headers:{'Content-Type':'application/json'},...options}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'We could not update your email preferences.');return d}
function showPrefs(d){const p=d.preferences||{};document.getElementById('prefOffers').checked=p.offers!==false;document.getElementById('prefTips').checked=p.tips!==false;document.getElementById('prefNews').checked=p.news!==false;form.classList.remove('hidden');statusEl.textContent=d.status==='unsubscribed'?'You are currently unsubscribed. Choose any topics below if you would like to rejoin.':'Choose what you would like Namdar to send you.'}
async function unsubscribe(){try{form.classList.add('hidden');statusEl.textContent='Unsubscribing…';await request({method:'POST',body:JSON.stringify({action:'unsubscribe'})});statusEl.textContent='You have been unsubscribed from Namdar marketing emails. Essential service emails will still be sent when needed.'}catch(e){statusEl.textContent=e.message;form.classList.remove('hidden')}}
async function load(){if(!token){statusEl.textContent='This email-preference link is incomplete.';return}if(q.get('action')==='unsubscribe'){await unsubscribe();return}try{showPrefs(await request())}catch(e){statusEl.textContent=e.message}}
form?.addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('savePreferences');btn.disabled=true;statusEl.textContent='Saving…';try{const d=await request({method:'POST',body:JSON.stringify({action:'preferences',preferences:{offers:document.getElementById('prefOffers').checked,tips:document.getElementById('prefTips').checked,news:document.getElementById('prefNews').checked}})});statusEl.textContent=d.status==='unsubscribed'?'All marketing topics are off. You are unsubscribed.':'Your Namdar email preferences have been saved.';showPrefs(d)}catch(err){statusEl.textContent=err.message}finally{btn.disabled=false}});
document.getElementById('unsubscribeAll')?.addEventListener('click',unsubscribe);
load();
