create table if not exists public.conversion_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type = 'postcode_checked'),
  visitor_id text not null check (char_length(visitor_id) between 8 and 96),
  service_key text not null check (char_length(service_key) between 1 and 40),
  postcode_area text,
  covered boolean,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_funnel_links (
  quote_id uuid primary key references public.quotes(id) on delete cascade,
  visitor_id text not null check (char_length(visitor_id) between 8 and 96),
  created_at timestamptz not null default now()
);

create table if not exists public.booking_job_costs (
  booking_id uuid primary key references public.bookings(id) on delete cascade,
  consumables_cost numeric not null default 0 check (consumables_cost >= 0),
  parking_cost numeric not null default 0 check (parking_cost >= 0),
  travel_cost numeric not null default 0 check (travel_cost >= 0),
  other_cost numeric not null default 0 check (other_cost >= 0),
  travel_minutes integer not null default 0 check (travel_minutes between 0 and 1440),
  travel_miles numeric not null default 0 check (travel_miles >= 0),
  notes text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.conversion_events enable row level security;
alter table public.quote_funnel_links enable row level security;
alter table public.booking_job_costs enable row level security;

revoke all on public.conversion_events from anon, authenticated;
revoke all on public.quote_funnel_links from anon, authenticated;
revoke all on public.booking_job_costs from anon, authenticated;

create index if not exists conversion_events_stage_lookup_idx on public.conversion_events(event_type, service_key, created_at desc);
create index if not exists conversion_events_visitor_lookup_idx on public.conversion_events(visitor_id, service_key, created_at desc);
create index if not exists quote_funnel_links_visitor_idx on public.quote_funnel_links(visitor_id, created_at desc);
create index if not exists booking_job_costs_updated_by_idx on public.booking_job_costs(updated_by);
create index if not exists booking_job_costs_updated_at_idx on public.booking_job_costs(updated_at desc);
