const {json,parseBody,db,authUser,userProfile,requireStaff,verifyTurnstile,env,auditLog,safeError}=require('../lib/server');
function pickFaq(message,items){const words=message.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);let best=null,score=0;for(const x of items||[]){const hay=(x.question+' '+(x.keywords||[]).join(' ')).toLowerCase();const s=words.reduce((n,w)=>n+(hay.includes(w)?1:0),0);if(s>score){score=s;best=x}}return score?best:null}
async function aiReply(message,faqs){const key=env('OPENAI_API_KEY'),model=env('OPENAI_MODEL');if(!key||!model)return null;const knowledge=(faqs||[]).map(x=>`Q: ${x.question}\nA: ${x.answer}`).join('\n\n');const input=`You are the Namdar website assistant for an exterior cleaning, handyman and 3D property services company. Be concise, friendly and factual. Only answer from the supplied business knowledge. Never invent a price; direct users to the quote form for pricing. If the user needs a human, billing help, a complaint, or something outside the knowledge, say you can create a support ticket.\n\nKNOWLEDGE:\n${knowledge}\n\nUSER: ${message}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input,max_output_tokens:220})});if(!r.ok)return null;const d=await r.json();if(d.output_text)return d.output_text;for(const o of d.output||[])for(const c of o.content||[])if(c.type==='output_text'&&c.text)return c.text;return null}
async function getSession({sessionId,guestToken,userId}){if(sessionId){const rows=await db(`chat_sessions?id=eq.${encodeURIComponent(sessionId)}&select=*`);const s=rows?.[0];if(!s)return null;if(userId&&s.customer_id===userId)return s;if(!userId&&guestToken&&s.guest_token===guestToken)return s;return null}return null}
module.exports=async function(req,res){try{if(req.method!=='POST')return json(res,405,{ok:false,error:'Method not allowed'});const b=parseBody(req);const action=String(b.action||'message');const user=await authUser(req);const profile=user?.id?await userProfile(user.id):null;
 if(action==='staff_reply'){const staffCtx=await requireStaff(req,'chat');const s=(await db(`chat_sessions?id=eq.${encodeURIComponent(b.sessionId)}&select=*`))?.[0];if(!s)return json(res,404,{ok:false,error:'Chat not found.'});const message=String(b.message||'').trim().slice(0,4000);if(!message)return json(res,400,{ok:false,error:'Reply required.'});await db('chat_messages',{method:'POST',body:{session_id:s.id,sender_id:user.id,sender_role:'staff',message}});await db(`chat_sessions?id=eq.${encodeURIComponent(s.id)}`,{method:'PATCH',body:{mode:'human',assigned_to:user.id,updated_at:new Date().toISOString()}});await auditLog(req,staffCtx,{action:'chat.reply',entityType:'chat_session',entityId:s.id,summary:'Replied to live chat',before:{mode:s.mode,status:s.status},after:{mode:'human',status:s.status},metadata:{messageLength:message.length}});return json(res,200,{ok:true})}
 if(action==='close'){const staffCtx=await requireStaff(req,'chat');const before=(await db(`chat_sessions?id=eq.${encodeURIComponent(b.sessionId)}&select=*&limit=1`))?.[0]||null;await db(`chat_sessions?id=eq.${encodeURIComponent(b.sessionId)}`,{method:'PATCH',body:{status:'closed',closed_at:new Date().toISOString(),updated_at:new Date().toISOString()}});await auditLog(req,staffCtx,{action:'chat.close',entityType:'chat_session',entityId:b.sessionId,summary:'Closed live chat session',before,after:{...before,status:'closed'}});return json(res,200,{ok:true})}
 let session=await getSession({sessionId:b.sessionId,guestToken:b.guestToken,userId:user?.id});
 if(!session&&!user?.id&&action==='message'){const turn=await verifyTurnstile(b.turnstileToken,req);if(!turn.ok)return json(res,400,{ok:false,error:turn.error})}
 if(!session){const rows=await db('chat_sessions',{method:'POST',prefer:'return=representation',body:{customer_id:user?.id||null,guest_name:user?.id?null:String(b.name||'Guest').slice(0,120),guest_email:user?.id?null:String(b.email||'').toLowerCase().slice(0,180),status:'open',mode:'assistant'}});session=rows[0]}
 if(action==='poll'){const msgs=await db(`chat_messages?session_id=eq.${encodeURIComponent(session.id)}&select=id,sender_role,message,created_at&order=created_at.asc`);return json(res,200,{ok:true,session:{id:session.id,guestToken:session.guest_token,mode:session.mode,status:session.status},messages:msgs||[]})}
 const message=String(b.message||'').trim().slice(0,4000);if(!message)return json(res,400,{ok:false,error:'Write a message.'});await db('chat_messages',{method:'POST',body:{session_id:session.id,sender_id:user?.id||null,sender_role:user?.id?'customer':'guest',message}});await db(`chat_sessions?id=eq.${encodeURIComponent(session.id)}`,{method:'PATCH',body:{updated_at:new Date().toISOString()}});
 const online=await db('staff_presence?online=eq.true&select=user_id,display_name,last_seen_at&limit=1');const staffOnline=!!online?.length;
 if(session.mode==='human'&&staffOnline)return json(res,200,{ok:true,session:{id:session.id,guestToken:session.guest_token,mode:'human'},reply:null,staffOnline:true});
 const faqs=await db('assistant_knowledge?active=eq.true&select=question,answer,keywords&order=sort_order.asc');let reply=await aiReply(message,faqs);if(!reply){const faq=pickFaq(message,faqs);reply=faq?.answer||'I can help with Namdar services, quotes, bookings, 3D tours and support. I am not certain about that question, so I can create a support ticket for the team.'}
 await db('chat_messages',{method:'POST',body:{session_id:session.id,sender_role:'assistant',message:reply}});return json(res,200,{ok:true,session:{id:session.id,guestToken:session.guest_token,mode:'assistant'},reply,staffOnline,offerTicket:/ticket|not certain|human/i.test(reply)});
}catch(e){return safeError(res,e)}};
