const { json, db, safeError, queryParam } = require('../lib/server');
const SERVICE_KEYS=new Set(['windows','gutters','roof','jetwash','handyman','tour3d']);
function distanceKm(a,b,c,d){const r=6371,toRad=x=>x*Math.PI/180,dLat=toRad(c-a),dLon=toRad(d-b),q=Math.sin(dLat/2)**2+Math.cos(toRad(a))*Math.cos(toRad(c))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
function cleanPostcode(value=''){const raw=String(value).trim().toUpperCase().replace(/\s+/g,'');return raw.length>3?`${raw.slice(0,-3)} ${raw.slice(-3)}`:raw}
function postcodeForQuery(value=''){return cleanPostcode(value).replace(/\s/g,'')}
function rowToLocation(p){return{postcode:p.postcode,country:p.country||'United Kingdom',countryCode:p.country_code||'GB',region:p.region||'',city:p.city||'',district:p.district||'',districtCode:p.district_code||'',ward:p.ward||'',longitude:p.longitude==null?null:Number(p.longitude),latitude:p.latitude==null?null:Number(p.latitude)}}
function postcodeParts(value=''){const full=postcodeForQuery(value),outward=full.length>3?full.slice(0,-3):full,sector=full.length>3?outward+full.slice(-3,-2):outward;return{full,outward,sector}}
function cleanRule(value=''){return String(value||'').trim().toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9*]/g,'')}
function matchPostcodeRule(postcode,rules=[]){const p=postcodeParts(postcode);let best=null;for(const raw of Array.isArray(rules)?rules:[]){const rule=cleanRule(raw);if(!rule)continue;let matched=false,rank=0,type='';if(rule.endsWith('*')){const prefix=rule.slice(0,-1);matched=!!prefix&&p.full.startsWith(prefix);rank=10+Math.min(prefix.length,8);type='wildcard'}else if(rule===p.full){matched=true;rank=40;type='full postcode'}else if(rule===p.sector){matched=true;rank=30;type='postcode sector'}else if(rule===p.outward){matched=true;rank=20;type='postcode district'}if(matched&&(!best||rank>best.rank))best={rule:raw,normalized:rule,rank,type}}return best}
function geometryOf(value){if(!value||typeof value!=='object')return null;if(value.type==='Feature')return value.geometry||null;return value}
function pointInRing(lng,lat,ring=[]){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=Number(ring[i]?.[0]),yi=Number(ring[i]?.[1]),xj=Number(ring[j]?.[0]),yj=Number(ring[j]?.[1]);if(![xi,yi,xj,yj].every(Number.isFinite))continue;const hit=((yi>lat)!==(yj>lat))&&(lng<(xj-xi)*(lat-yi)/((yj-yi)||1e-12)+xi);if(hit)inside=!inside}return inside}
function pointInPolygon(lng,lat,coords=[]){if(!coords.length||!pointInRing(lng,lat,coords[0]))return false;for(let i=1;i<coords.length;i++)if(pointInRing(lng,lat,coords[i]))return false;return true}
function pointInGeometry(lng,lat,value){const g=geometryOf(value);if(!g)return false;if(g.type==='Polygon')return pointInPolygon(lng,lat,g.coordinates||[]);if(g.type==='MultiPolygon')return(g.coordinates||[]).some(poly=>pointInPolygon(lng,lat,poly));return false}
function norm(v=''){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function areaSupportsService(a,service=''){const keys=Array.isArray(a.service_keys)?a.service_keys:[];return !service||!keys.length||keys.includes(service)}
function evaluateArea(p,a){const lat=Number(p.latitude),lng=Number(p.longitude),alat=Number(a.latitude),alng=Number(a.longitude),radius=Number(a.radius_km||0),km=[lat,lng,alat,alng].every(Number.isFinite)?distanceKm(lat,lng,alat,alng):null;const excluded=matchPostcodeRule(p.postcode,a.exclude_postcodes||[]);if(excluded)return{...a,distanceKm:km==null?null:Number(km.toFixed(2)),covered:false,coverageMethod:'postcode_exclude',coverageReason:`Excluded by ${excluded.type} rule ${excluded.rule}`,matchedRule:excluded.rule,_rank:160+excluded.rank};const included=matchPostcodeRule(p.postcode,a.include_postcodes||[]);if(included)return{...a,distanceKm:km==null?null:Number(km.toFixed(2)),covered:true,coverageMethod:'postcode_include',coverageReason:`Included by ${included.type} rule ${included.rule}`,matchedRule:included.rule,_rank:140+included.rank};const mode=['administrative','polygon'].includes(a.coverage_mode)?a.coverage_mode:'radius';if(mode==='administrative'){const codes=(a.admin_area_codes||[]).map(x=>String(x).toUpperCase()),names=(a.admin_area_names||[]).map(norm),code=String(p.districtCode||'').toUpperCase(),name=norm(p.district),matched=(code&&codes.includes(code))||(!code&&name&&names.includes(name))||(name&&names.includes(name));return{...a,distanceKm:km==null?null:Number(km.toFixed(2)),covered:!!matched,coverageMethod:'administrative_area',coverageReason:matched?`Inside selected council/borough ${p.district||code}`:`${p.district||'This postcode'} is not in a selected council/borough`,matchedRule:matched?(code||p.district):null,_rank:matched?100:25}}if(mode==='polygon'&&geometryOf(a.geojson)){const inside=Number.isFinite(lat)&&Number.isFinite(lng)&&pointInGeometry(lng,lat,a.geojson);return{...a,distanceKm:km==null?null:Number(km.toFixed(2)),covered:inside,coverageMethod:'polygon',coverageReason:inside?'Inside the custom service boundary':'Outside the custom service boundary',matchedRule:null,_rank:inside?60:20}}const inside=km!=null&&Number.isFinite(radius)&&radius>0&&km<=radius;return{...a,distanceKm:km==null?null:Number(km.toFixed(2)),covered:inside,coverageMethod:'radius',coverageReason:inside?`Inside the ${radius} km service radius`:`Outside the ${radius} km service radius`,matchedRule:null,_rank:inside?40:10}}
async function serviceAreaFor(p,service=''){const areas=await db('service_areas?active=eq.true&select=id,label,country_code,region,city,district,latitude,longitude,radius_km,geojson,coverage_mode,include_postcodes,exclude_postcodes,admin_area_codes,admin_area_names,service_keys,priority');const eligible=(areas||[]).filter(a=>areaSupportsService(a,service)),evaluated=eligible.map(a=>evaluateArea(p,a));if(!evaluated.length)return{area:null,configured:false,covered:false};const byDecision=(a,b)=>(Number(b.priority??100)-Number(a.priority??100))||(b._rank-a._rank)||((a.distanceKm??Infinity)-(b.distanceKm??Infinity))||String(a.label||'').localeCompare(String(b.label||'')),covered=evaluated.filter(x=>x.covered).sort(byDecision),chosen=covered[0]||evaluated.sort((a,b)=>(Number(b.priority??100)-Number(a.priority??100))||((a.distanceKm??Infinity)-(b.distanceKm??Infinity))||(b._rank-a._rank))[0];if(!chosen)return{area:null,configured:true,covered:false};const{_rank,...safe}=chosen;return{area:safe,configured:true,covered:covered.length>0}}
async function fromCache(postcode){const rows=await db(`postcode_directory?postcode=eq.${encodeURIComponent(postcode)}&select=*&limit=1`);return rows?.[0]||null}
async function fetchPublicPostcode(postcode){const r=await fetch(`https://api.postcodes.io/postcodes/${encodeURIComponent(postcodeForQuery(postcode))}`),d=await r.json().catch(()=>null);if(!r.ok||!d?.result)return null;const x=d.result,region=x.region||'',isLondon=region.toLowerCase()==='london',city=isLondon?'London':(x.admin_district||x.parliamentary_constituency||region||''),district=isLondon?(x.admin_district||x.admin_ward||''):(x.admin_district||x.admin_ward||x.parish||'');return{postcode:cleanPostcode(x.postcode),country:'United Kingdom',country_code:'GB',region,city,district,district_code:x.codes?.admin_district||'',ward:x.admin_ward||'',longitude:x.longitude,latitude:x.latitude,source:'postcodes.io',verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}}
module.exports=async function handler(req,res){try{if(req.method!=='GET')return json(res,405,{ok:false,error:'Method not allowed'});const input=cleanPostcode(queryParam(req,'postcode')||''),service=String(queryParam(req,'service')||'').trim();if(!input)return json(res,400,{ok:false,error:'Enter a postcode.'});if(service&&!SERVICE_KEYS.has(service))return json(res,400,{ok:false,error:'Unknown service.'});let cached=await fromCache(input),row=cached;const stale=!cached||!cached.district_code||!cached.verified_at||(Date.now()-new Date(cached.verified_at).getTime())>1000*60*60*24*90;if(stale){const fresh=await fetchPublicPostcode(input).catch(()=>null);if(fresh){const saved=await db('postcode_directory?on_conflict=postcode',{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:fresh});row=saved?.[0]||fresh}}if(!row)return json(res,404,{ok:false,error:'We could not verify that UK postcode. Check it and try again.'});const p=rowToLocation(row),coverage=await serviceAreaFor(p,service);return json(res,200,{ok:true,...p,area:coverage.area,coverage:{service:service||null,configured:coverage.configured,covered:coverage.covered},source:'namdar-postcode-directory',cached:Boolean(cached)})}catch(e){return safeError(res,e)}};
