const crypto=require('crypto');
const {json,db,env,createStaffNotification,safeError}=require('../lib/server');
function header(req,name){return String(req.headers?.[name]||req.headers?.[name.toLowerCase()]||'')}
async function rawBody(req){if(Buffer.isBuffer(req.body))return req.body.toString('utf8');if(typeof req.body==='string')return req.body;if(req.body&&typeof req.body==='object')return JSON.stringify(req.body);let out='';for await(const c of req)out+=Buffer.isBuffer(c)?c.toString('utf8'):String(c);return out}
function verify(payload,req){const secret=String(env('RESEND_WEBHOOK_SECRET')||'');if(!secret)return false;const id=header(req,'svix-id'),ts=header(req,'svix-timestamp'),sig=header(req,'svix-signature');if(!id||!ts||!sig)return false;const n=Number(ts);if(!Number.isFinite(n)||Math.abs(Date.now()/1000-n)>300)return false;let key=secret.replace(/^whsec_/,'');try{key=Buffer.from(key,'base64')}catch{return false}const digest=crypto.createHmac('sha256',key).update(`${id}.${ts}.${payload}`).digest('base64');const options=sig.split(' ').map(x=>x.replace(/^v1,/,'').trim()).filter(Boolean);return options.some(x=>{try{const a=Buffer.from(x),b=Buffer.from(digest);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}})}
function emailOnly(v=''){const m=String(v||'').match(/<([^<>\s]+@[^<>\s]+)>/);return String(m?m[1]:v).trim().toLowerCase().replace(/^mailto:/,'').slice(0,240)}
function displayName(v=''){const s=String(v||'').trim(),m=s.match(/^(.+?)\s*<[^>]+>$/);return (m?m[1].replace(/^['"]|['"]$/g,'').trim():'').slice(0,160)||null}
function domainOf(v=''){const e=emailOnly(v),at=e.lastIndexOf('@');return at>0?e.slice(at+1).replace(/^\.+|\.+$/g,'').slice(0,240):''}
const DIRECT_MAILBOXES=new Set(['support','bookings','accounts','billing','hello']);
const DANGEROUS_EXTENSIONS=new Set(['exe','scr','com','pif','bat','cmd','ps1','vbs','vbe','js','jse','wsf','wsh','hta','msi','msp','dll','cpl','jar','apk','iso','img','lnk','reg','docm','xlsm','pptm']);
const CAUTION_EXTENSIONS=new Set(['zip','rar','7z','gz','bz2','xz','tar','html','htm','svg','eml']);
function mailboxOf(to=[]){for(const v of Array.isArray(to)?to:[to]){const e=emailOnly(v),local=(e.split('@')[0]||'').toLowerCase();if(!local)continue;const reply=local.match(/^reply[+._-]([a-z0-9]{8,40})$/i);if(reply)return{mailbox:'support',replyToken:reply[1],recipient:e};const clean=local.split('+')[0].replace(/[^a-z0-9._-]/gi,'').toLowerCase();if(DIRECT_MAILBOXES.has(clean))return{mailbox:clean,replyToken:null,recipient:e}}return null}
function permissionFor(mailbox){if(mailbox==='bookings')return'bookings';if(['accounts','billing'].includes(mailbox))return'payments';if(mailbox==='support')return'tickets';return'inbox'}
function priorityFor(subject='',body=''){const s=`${subject} ${body}`.toLowerCase();return /urgent|emergency|danger|unsafe|injur|complaint|chargeback|phish|fraud/.test(s)?'urgent':/cancel|payment|refund|problem|issue|damage/.test(s)?'high':'normal'}
function getHeader(headers,name){if(!headers)return'';if(Array.isArray(headers)){const x=headers.find(h=>String(h?.name||h?.key||'').toLowerCase()===name.toLowerCase());return String(x?.value||'')}for(const [k,v] of Object.entries(headers))if(k.toLowerCase()===name.toLowerCase())return Array.isArray(v)?String(v[0]||''):String(v||'');return''}
function safeSubject(v=''){return String(v||'Email to Namdar').replace(/[\r\n]+/g,' ').replace(/\s{2,}/g,' ').trim().slice(0,300)||'Email to Namdar'}
function authResult(headers={}){const raw=String(getHeader(headers,'authentication-results')||getHeader(headers,'arc-authentication-results')||'').toLowerCase();const value=k=>raw.match(new RegExp(`\\b${k}=([a-z0-9_-]+)`))?.[1]||'';const dmarc=value('dmarc'),spf=value('spf'),dkim=value('dkim');if(dmarc==='fail')return{quarantine:true,score:100,status:'failed',reason:'Sender authentication failed (DMARC)'};if(spf==='fail'&&dkim==='fail')return{quarantine:false,score:45,status:'suspicious',reason:'SPF and DKIM both failed'};if(dmarc==='pass'||dkim==='pass'||spf==='pass')return{quarantine:false,score:0,status:'passed',reason:null};return{quarantine:false,score:0,status:'unknown',reason:null}}
function extensionOf(filename=''){const clean=String(filename||'').toLowerCase().split(/[?#]/)[0],part=clean.includes('.')?clean.split('.').pop():'';return part.replace(/[^a-z0-9]/g,'').slice(0,12)}
function safeAttachment(a={}){const filename=String(a.filename||'attachment').replace(/[\r\n]+/g,' ').slice(0,240),contentType=String(a.content_type||'').toLowerCase().slice(0,160),size=Math.max(0,Number(a.size||0)||0),ext=extensionOf(filename);let risk='',risk_reason='';if(DANGEROUS_EXTENSIONS.has(ext)||/x-msdownload|x-dosexec|x-sh|x-bat|java-archive|portable-executable/.test(contentType)){risk='blocked';risk_reason=`Potentially unsafe attachment type${ext?` (.${ext})`:''}`}else if(CAUTION_EXTENSIONS.has(ext)){risk='caution';risk_reason=`Archive or active-content attachment${ext?` (.${ext})`:''}`}else if(size>15*1024*1024){risk='caution';risk_reason='Large attachment'}return{id:String(a.id||'').slice(0,200),filename,content_type:contentType,size,risk,risk_reason}}
function assessAttachments(items=[]){const blocked=items.find(a=>a.risk==='blocked');if(blocked)return{quarantine:true,score:100,reason:blocked.risk_reason||'Potentially unsafe attachment',extraScore:0};let extraScore=0;const reasons=[];const caution=items.filter(a=>a.risk==='caution');if(caution.length){extraScore+=Math.min(30,caution.length*15);reasons.push(caution[0].risk_reason||'Caution attachment')}if(items.length>10){extraScore+=20;reasons.push('Unusually many attachments')}const total=items.reduce((a,x)=>a+Number(x.size||0),0);if(total>30*1024*1024){extraScore+=25;reasons.push('Large total attachment size')}return{quarantine:false,score:Math.min(55,extraScore),reason:reasons.slice(0,2).join(' · ')||null,extraScore}}
function campaignFingerprint(subject='',body=''){const normalized=`${subject}\n${body}`.toLowerCase().replace(/https?:\/\/\S+/g,'<url>').replace(/\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b/g,'<email>').replace(/\s+/g,' ').trim().slice(0,24000);return normalized?crypto.createHash('sha256').update(normalized).digest('hex'):''}
async function receivedEmail(id){const r=await fetch(`https://api.resend.com/emails/receiving/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${env('RESEND_API_KEY')}`,Accept:'application/json'}});if(!r.ok)throw new Error(`Could not retrieve inbound email (${r.status}).`);return r.json()}
async function blockedRule(from){const email=emailOnly(from),domain=domainOf(email);if(!email)return null;const [sender,domainRule]=await Promise.all([db(`support_inbox_blocklist?active=eq.true&scope=eq.sender&value=eq.${encodeURIComponent(email)}&select=id,scope,value,reason&limit=1`).catch(()=>[]),domain?db(`support_inbox_blocklist?active=eq.true&scope=eq.domain&value=eq.${encodeURIComponent(domain)}&select=id,scope,value,reason&limit=1`).catch(()=>[]):Promise.resolve([])]);return sender?.[0]||domainRule?.[0]||null}
function assessSpam({subject='',body='',headers={},knownCustomer=false,replyContext=false,authScore=0,attachmentScore=0,attachmentReason=null}){if(knownCustomer||replyContext)return{isSpam:false,score:0,reason:null,source:null};let score=Math.max(0,Number(authScore||0))+Math.max(0,Number(attachmentScore||0));const reasons=[];const text=`${subject}\n${body}`.toLowerCase();const add=(points,reason)=>{score+=points;if(reason&&!reasons.includes(reason))reasons.push(reason)};if(authScore>=40)reasons.push('Sender authentication warning');if(attachmentReason)reasons.push(attachmentReason);const upstream=String(getHeader(headers,'x-spam-status')||'').toLowerCase();if(/\byes\b|spam/.test(upstream))add(80,'Upstream spam header');if(getHeader(headers,'list-unsubscribe'))add(30,'Bulk-mail unsubscribe header');if(/bulk|list|junk/.test(String(getHeader(headers,'precedence')||'').toLowerCase()))add(30,'Bulk-mail precedence header');const patterns=[[/\bseo\b|search engine optimization|google rankings?|rank (?:your )?(?:site|website)|backlinks?|domain authority/i,35,'SEO/link-building outreach'],[/guest posts?|link insertion|link building|sponsored (?:post|article)/i,35,'Guest-post/link outreach'],[/lead generation|appointment setting|cold email|digital marketing agency|marketing services/i,30,'Cold sales/marketing outreach'],[/ai[- ]driven growth|grow your (?:business|website)|increase (?:your )?(?:website )?traffic|more qualified leads/i,30,'Generic growth outreach'],[/web(?:site)? redesign|web design services?|website development services?/i,25,'Website sales outreach'],[/noticed your website|quick question about your website|more (?:clients|customers) for/i,20,'Unsolicited website outreach']];for(const [re,points,reason] of patterns)if(re.test(text))add(points,reason);const urls=(text.match(/https?:\/\/|www\./g)||[]).length;if(urls>=3)add(20,'Multiple external links');else if(urls>=1)add(5,'External link');score=Math.min(100,score);return{isSpam:score>=60,score,reason:reasons.slice(0,4).join(' · ')||null,source:score>=60?'automatic':null}}
async function highFrequencyUnknownSender(from){const since=new Date(Date.now()-60*60*1000).toISOString();const rows=await db(`support_inbox_messages?direction=eq.inbound&from_email=eq.${encodeURIComponent(from)}&sent_at=gte.${encodeURIComponent(since)}&select=id&limit=9`).catch(()=>[]);return(rows||[]).length>=8}
async function repeatedCampaign({from,subject,body}){const fp=campaignFingerprint(subject,body);if(!fp||body.length<80)return false;const since=new Date(Date.now()-14*24*60*60*1000).toISOString();const rows=await db(`support_inbox_messages?direction=eq.inbound&subject=eq.${encodeURIComponent(subject)}&sent_at=gte.${encodeURIComponent(since)}&select=from_email,body_text&order=sent_at.desc&limit=40`).catch(()=>[]),senders=new Set();for(const row of rows||[]){const sender=emailOnly(row.from_email);if(!sender||sender===from)continue;if(campaignFingerprint(subject,String(row.body_text||''))===fp)senders.add(sender)}return senders.size>=2}
async function duplicateMessageId(messageId,from){if(!messageId)return null;return(await db(`support_inbox_messages?direction=eq.inbound&email_message_id=eq.${encodeURIComponent(messageId)}&from_email=eq.${encodeURIComponent(from)}&select=id,thread_id&limit=1`).catch(()=>[]))?.[0]||null}
function storedHeaders(headers,messageId,inReplyTo,auth){const take=(name,max=1200)=>String(getHeader(headers,name)||'').slice(0,max);return{'message-id':messageId,'in-reply-to':inReplyTo,'authentication-results':take('authentication-results',2400),'arc-authentication-results':take('arc-authentication-results',2400),'received-spf':take('received-spf'), 'x-spam-status':take('x-spam-status'),'auto-submitted':take('auto-submitted'),'precedence':take('precedence'),'namdar-auth-status':auth.status||'unknown'}}
module.exports=async function(req,res){try{
  if(req.method!=='POST')return json(res,405,{ok:false,error:'Method not allowed'});const payload=await rawBody(req);if(!verify(payload,req))return json(res,400,{ok:false,error:'Invalid webhook signature.'});
  const event=JSON.parse(payload);if(event.type!=='email.received')return json(res,200,{ok:true,ignored:true});const meta=event.data||{},emailId=String(meta.email_id||'');if(!emailId)return json(res,200,{ok:true,ignored:true});
  const duplicate=(await db(`support_inbox_messages?resend_email_id=eq.${encodeURIComponent(emailId)}&select=id&limit=1`).catch(()=>[]))?.[0];if(duplicate)return json(res,200,{ok:true,duplicate:true});
  const metaRoute=mailboxOf(meta.to||[]);if(!metaRoute)return json(res,200,{ok:true,ignored:true,reason:'unknown_recipient'});const metaFrom=emailOnly(meta.from||'');if(domainOf(metaFrom)==='namdar.co.uk')return json(res,200,{ok:true,ignored:true,reason:'internal_sender'});const metaMessageId=String(meta.message_id||'').slice(0,1000)||null;if(metaFrom&&metaMessageId&&await duplicateMessageId(metaMessageId,metaFrom))return json(res,200,{ok:true,duplicate:true,reason:'message_id'});
  const full=await receivedEmail(emailId),from=emailOnly(full.from||meta.from),name=displayName(full.from||meta.from),to=Array.isArray(full.to)?full.to:(meta.to||[]),cc=Array.isArray(full.cc)?full.cc:(meta.cc||[]),subject=safeSubject(full.subject||meta.subject||'Email to Namdar'),body=String(full.text||'').trim().slice(0,50000),html=String(full.html||'').slice(0,50000),headers=full.headers||{},messageId=String(full.message_id||meta.message_id||getHeader(headers,'message-id')||'').slice(0,1000)||null,inReplyTo=String(getHeader(headers,'in-reply-to')||'').slice(0,1000)||null,route=mailboxOf(to),permission=permissionFor(route?.mailbox||'support');
  if(!route)return json(res,200,{ok:true,ignored:true,reason:'unknown_recipient'});if(!from||!from.includes('@'))return json(res,200,{ok:true,ignored:true,reason:'invalid_sender'});if(domainOf(from)==='namdar.co.uk')return json(res,200,{ok:true,ignored:true,reason:'internal_sender'});if(await duplicateMessageId(messageId,from))return json(res,200,{ok:true,duplicate:true,reason:'message_id'});
  let thread=null;if(route.replyToken)thread=(await db(`support_inbox_threads?reply_token=eq.${encodeURIComponent(route.replyToken)}&select=*&limit=1`))?.[0]||null;if(route.replyToken&&!thread)return json(res,200,{ok:true,ignored:true,reason:'invalid_reply_token'});
  if(!thread&&inReplyTo){const m=(await db(`support_inbox_messages?email_message_id=eq.${encodeURIComponent(inReplyTo)}&select=thread_id&limit=1`).catch(()=>[]))?.[0];if(m?.thread_id)thread=(await db(`support_inbox_threads?id=eq.${encodeURIComponent(m.thread_id)}&select=*&limit=1`))?.[0]||null}
  const customer=(await db(`profiles?email=eq.${encodeURIComponent(from)}&role=eq.customer&select=id,full_name&limit=1`).catch(()=>[]))?.[0]||null,replyContext=!!thread,block=await blockedRule(from),auth=authResult(headers),attachments=(full.attachments||meta.attachments||[]).slice(0,20).map(safeAttachment),attachmentAssessment=assessAttachments(attachments);
  let assessment;if(block)assessment={isSpam:true,score:100,reason:block.reason||(block.scope==='domain'?`Blocked domain @${block.value}`:`Blocked sender ${block.value}`),source:block.scope==='domain'?'blocked_domain':'blocked_sender'};else if(auth.quarantine)assessment={isSpam:true,score:100,reason:auth.reason,source:'security'};else if(attachmentAssessment.quarantine)assessment={isSpam:true,score:100,reason:attachmentAssessment.reason,source:'security'};else assessment=assessSpam({subject,body,headers,knownCustomer:!!customer,replyContext,authScore:auth.score,attachmentScore:attachmentAssessment.score,attachmentReason:attachmentAssessment.reason});
  if(!block&&!assessment.isSpam&&!customer&&!replyContext&&await repeatedCampaign({from,subject,body}))assessment={isSpam:true,score:95,reason:'Repeated campaign content from multiple senders',source:'campaign'};
  if(!block&&!assessment.isSpam&&!customer&&!replyContext&&await highFrequencyUnknownSender(from))assessment={isSpam:true,score:100,reason:'High-frequency unknown sender',source:'automatic'};
  let quarantined=!!block||assessment.isSpam||thread?.status==='spam';if(!thread&&quarantined){thread=(await db(`support_inbox_threads?customer_email=eq.${encodeURIComponent(from)}&mailbox=eq.${encodeURIComponent(route.mailbox)}&status=eq.spam&select=*&order=updated_at.desc&limit=1`).catch(()=>[]))?.[0]||null}
  const spamSource=assessment.isSpam?(assessment.source||'automatic'):thread?.spam_source||null,spamReason=assessment.isSpam?assessment.reason:thread?.spam_reason||null,spamScore=assessment.isSpam?assessment.score:Number(thread?.spam_score||0);
  if(!thread){thread=(await db('support_inbox_threads',{method:'POST',prefer:'return=representation',body:{mailbox:route.mailbox,permission_key:permission,customer_id:customer?.id||null,customer_email:from,customer_name:customer?.full_name||name,subject,status:quarantined?'spam':'awaiting_staff',priority:priorityFor(subject,body),unread_count:0,last_message_at:new Date().toISOString(),spam_source:quarantined?spamSource:null,spam_reason:quarantined?spamReason:null,spam_score:quarantined?spamScore:0}}))?.[0]}
  if(!thread)return json(res,500,{ok:false,error:'Could not create inbox thread.'});quarantined=quarantined||thread.status==='spam';
  await db('support_inbox_messages',{method:'POST',body:{thread_id:thread.id,direction:'inbound',resend_email_id:emailId,email_message_id:messageId,in_reply_to:inReplyTo,from_email:from,to_emails:(to||[]).map(emailOnly).filter(Boolean).slice(0,20),cc_emails:(cc||[]).map(emailOnly).filter(Boolean).slice(0,20),subject,body_html:html||null,body_text:body||'(No plain-text body supplied)',attachments,headers:storedHeaders(headers,messageId,inReplyTo,auth),delivery_status:'received',sent_at:full.created_at||meta.created_at||new Date().toISOString()}});
  const unread=quarantined?0:Number(thread.unread_count||0)+1,threadPatch={customer_id:thread.customer_id||customer?.id||null,customer_name:thread.customer_name||customer?.full_name||name,status:quarantined?'spam':'awaiting_staff',unread_count:unread,last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(quarantined){threadPatch.spam_source=spamSource||thread.spam_source||'automatic';threadPatch.spam_reason=spamReason||thread.spam_reason||'Quarantined by Namdar inbox protection';threadPatch.spam_score=Math.max(spamScore,Number(thread.spam_score||0))}await db(`support_inbox_threads?id=eq.${encodeURIComponent(thread.id)}`,{method:'PATCH',body:threadPatch});
  if(quarantined)return json(res,200,{ok:true,quarantined:true});await createStaffNotification({type:'inbound_email',title:`New ${route.mailbox} email`,body:`${customer?.full_name||name||from} · ${subject}`,targetPath:`/admin?tab=inbox&thread=${encodeURIComponent(thread.id)}`,permissionKey:permission,entityType:'support_inbox_thread',entityId:thread.id,priority:thread.priority||priorityFor(subject,body),dedupeKey:`inbound-email:${emailId}`});return json(res,200,{ok:true});
}catch(e){return safeError(res,e)}};
