const crypto=require('crypto');
const {json,db,env,createStaffNotification,safeError}=require('../lib/server');
function header(req,name){return String(req.headers?.[name]||req.headers?.[name.toLowerCase()]||'')}
async function rawBody(req){if(Buffer.isBuffer(req.body))return req.body.toString('utf8');if(typeof req.body==='string')return req.body;if(req.body&&typeof req.body==='object')return JSON.stringify(req.body);let out='';for await(const c of req)out+=Buffer.isBuffer(c)?c.toString('utf8'):String(c);return out}
function verify(payload,req){const secret=String(env('RESEND_WEBHOOK_SECRET')||'');if(!secret)return false;const id=header(req,'svix-id'),ts=header(req,'svix-timestamp'),sig=header(req,'svix-signature');if(!id||!ts||!sig)return false;const n=Number(ts);if(!Number.isFinite(n)||Math.abs(Date.now()/1000-n)>300)return false;let key=secret.replace(/^whsec_/,'');try{key=Buffer.from(key,'base64')}catch{return false}const digest=crypto.createHmac('sha256',key).update(`${id}.${ts}.${payload}`).digest('base64');const options=sig.split(' ').map(x=>x.replace(/^v1,/,'').trim()).filter(Boolean);return options.some(x=>{try{const a=Buffer.from(x),b=Buffer.from(digest);return a.length===b.length&&crypto.timingSafeEqual(a,b)}catch{return false}})}
function emailOnly(v=''){const m=String(v||'').match(/<([^<>\s]+@[^<>\s]+)>/);return String(m?m[1]:v).trim().toLowerCase().replace(/^mailto:/,'').slice(0,240)}
function displayName(v=''){const s=String(v||'').trim(),m=s.match(/^(.+?)\s*<[^>]+>$/);return (m?m[1].replace(/^['"]|['"]$/g,'').trim():'').slice(0,160)||null}
function mailboxOf(to=[]){for(const v of Array.isArray(to)?to:[to]){const e=emailOnly(v),local=e.split('@')[0]||'';const reply=local.match(/^reply[+._-]([a-z0-9]{8,40})$/i);if(reply)return{mailbox:'support',replyToken:reply[1]};const clean=local.split('+')[0].replace(/[^a-z0-9._-]/gi,'').toLowerCase();if(clean)return{mailbox:['support','bookings','accounts','billing','hello'].includes(clean)?clean:'support',replyToken:null}}return{mailbox:'support',replyToken:null}}
function permissionFor(mailbox){if(mailbox==='bookings')return'bookings';if(['accounts','billing'].includes(mailbox))return'payments';if(mailbox==='support')return'tickets';return'inbox'}
function priorityFor(subject='',body=''){const s=`${subject} ${body}`.toLowerCase();return /urgent|emergency|danger|unsafe|injur|complaint|chargeback/.test(s)?'urgent':/cancel|payment|refund|problem|issue|damage/.test(s)?'high':'normal'}
function getHeader(headers,name){if(!headers)return'';if(Array.isArray(headers)){const x=headers.find(h=>String(h?.name||h?.key||'').toLowerCase()===name.toLowerCase());return String(x?.value||'')}for(const [k,v] of Object.entries(headers))if(k.toLowerCase()===name.toLowerCase())return Array.isArray(v)?String(v[0]||''):String(v||'');return''}
async function receivedEmail(id){const r=await fetch(`https://api.resend.com/emails/receiving/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${env('RESEND_API_KEY')}`,Accept:'application/json'}});if(!r.ok)throw new Error(`Could not retrieve inbound email (${r.status}).`);return r.json()}
module.exports=async function(req,res){try{
  if(req.method!=='POST')return json(res,405,{ok:false,error:'Method not allowed'});const payload=await rawBody(req);if(!verify(payload,req))return json(res,400,{ok:false,error:'Invalid webhook signature.'});
  const event=JSON.parse(payload);if(event.type!=='email.received')return json(res,200,{ok:true,ignored:true});const meta=event.data||{},emailId=String(meta.email_id||'');if(!emailId)return json(res,200,{ok:true,ignored:true});
  const duplicate=(await db(`support_inbox_messages?resend_email_id=eq.${encodeURIComponent(emailId)}&select=id&limit=1`).catch(()=>[]))?.[0];if(duplicate)return json(res,200,{ok:true,duplicate:true});
  const full=await receivedEmail(emailId),from=emailOnly(full.from||meta.from),name=displayName(full.from||meta.from),to=Array.isArray(full.to)?full.to:(meta.to||[]),cc=Array.isArray(full.cc)?full.cc:(meta.cc||[]),subject=String(full.subject||meta.subject||'Email to Namdar').trim().slice(0,300),body=String(full.text||'').trim().slice(0,50000),html=String(full.html||'').slice(0,50000),headers=full.headers||{},messageId=String(full.message_id||meta.message_id||getHeader(headers,'message-id')||'').slice(0,1000)||null,inReplyTo=String(getHeader(headers,'in-reply-to')||'').slice(0,1000)||null,route=mailboxOf(to),permission=permissionFor(route.mailbox);
  if(!from||!from.includes('@'))return json(res,200,{ok:true,ignored:true});
  let thread=null;if(route.replyToken)thread=(await db(`support_inbox_threads?reply_token=eq.${encodeURIComponent(route.replyToken)}&select=*&limit=1`))?.[0]||null;
  if(!thread&&inReplyTo){const m=(await db(`support_inbox_messages?email_message_id=eq.${encodeURIComponent(inReplyTo)}&select=thread_id&limit=1`).catch(()=>[]))?.[0];if(m?.thread_id)thread=(await db(`support_inbox_threads?id=eq.${encodeURIComponent(m.thread_id)}&select=*&limit=1`))?.[0]||null}
  let customer=(await db(`profiles?email=eq.${encodeURIComponent(from)}&role=eq.customer&select=id,full_name&limit=1`).catch(()=>[]))?.[0]||null;
  if(!thread){thread=(await db('support_inbox_threads',{method:'POST',prefer:'return=representation',body:{mailbox:route.mailbox,permission_key:permission,customer_id:customer?.id||null,customer_email:from,customer_name:customer?.full_name||name,subject,status:'awaiting_staff',priority:priorityFor(subject,body),unread_count:0,last_message_at:new Date().toISOString()}}))?.[0]}
  if(!thread)return json(res,500,{ok:false,error:'Could not create inbox thread.'});
  const attachments=(full.attachments||meta.attachments||[]).slice(0,20).map(a=>({id:String(a.id||'').slice(0,200),filename:String(a.filename||'attachment').slice(0,240),content_type:String(a.content_type||'').slice(0,160),size:Number(a.size||0)||0}));
  await db('support_inbox_messages',{method:'POST',body:{thread_id:thread.id,direction:'inbound',resend_email_id:emailId,email_message_id:messageId,in_reply_to:inReplyTo,from_email:from,to_emails:(to||[]).map(emailOnly).filter(Boolean).slice(0,20),cc_emails:(cc||[]).map(emailOnly).filter(Boolean).slice(0,20),subject,body_html:html||null,body_text:body||'(No plain-text body supplied)',attachments,headers:{'message-id':messageId,'in-reply-to':inReplyTo},delivery_status:'received',sent_at:full.created_at||meta.created_at||new Date().toISOString()}});
  const unread=Number(thread.unread_count||0)+1;await db(`support_inbox_threads?id=eq.${encodeURIComponent(thread.id)}`,{method:'PATCH',body:{customer_id:thread.customer_id||customer?.id||null,customer_name:thread.customer_name||customer?.full_name||name,status:'awaiting_staff',unread_count:unread,last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()}});
  await createStaffNotification({type:'inbound_email',title:`New ${route.mailbox} email`,body:`${customer?.full_name||name||from} · ${subject}`,targetPath:`/admin?tab=inbox&thread=${encodeURIComponent(thread.id)}`,permissionKey:permission,entityType:'support_inbox_thread',entityId:thread.id,priority:thread.priority||priorityFor(subject,body),dedupeKey:`inbound-email:${emailId}`});
  return json(res,200,{ok:true});
}catch(e){return safeError(res,e)}};
