const {json,parseBody,queryParam,db,requireStaff,sendEmail,auditLog,createStaffNotification,env,safeError}=require('../lib/server');
async function context(req){const base=await requireStaff(req);if(base.profile.role==='admin')return{...base,isAdmin:true,perms:{all:true}};const a=(await db(`staff_access?user_id=eq.${encodeURIComponent(base.user.id)}&select=permissions,active&limit=1`))?.[0];return{...base,isAdmin:false,perms:a?.active?(a.permissions||{}):{}}}
function canInbox(ctx){return ctx.isAdmin||ctx.perms?.inbox===true||ctx.perms?.tickets===true||ctx.perms?.bookings===true||ctx.perms?.payments===true}
function visibleThread(t,ctx){if(t.target_user_id&&t.target_user_id!==ctx.user.id)return false;if(ctx.isAdmin)return true;const permission=String(t.permission_key||'inbox');return ctx.perms?.[permission]===true}
function parseMailbox(v='support'){const x=String(v||'support').toLowerCase().replace(/[^a-z0-9._-]/g,'');return['support','bookings','accounts','billing','hello'].includes(x)?x:'support'}
function fromFor(mailbox){const local=parseMailbox(mailbox),label=local==='bookings'?'Namdar Bookings':(['accounts','billing'].includes(local)?'Namdar Accounts':local==='hello'?'Namdar':'Namdar Support');return `${label} <${local==='billing'?'accounts':local}@namdar.co.uk>`}
function inboundReply(thread){const domain=String(env('NAMDAR_INBOUND_DOMAIN')||'').trim().toLowerCase().replace(/^@/,'');return domain?`reply+${thread.reply_token}@${domain}`:(env('NAMDAR_SUPPORT_EMAIL')||'support@namdar.co.uk')}
function normalizeEmail(v=''){return String(v||'').trim().toLowerCase().replace(/^mailto:/,'').slice(0,240)}
function domainOf(v=''){const e=normalizeEmail(v),at=e.lastIndexOf('@');return at>0?e.slice(at+1).replace(/^\.+|\.+$/g,'').slice(0,240):''}
const PROTECTED_SHARED_DOMAINS=new Set(['gmail.com','googlemail.com','outlook.com','hotmail.com','live.com','yahoo.com','icloud.com','me.com','proton.me','protonmail.com','aol.com','namdar.co.uk']);
async function getThread(id,ctx){const t=(await db(`support_inbox_threads?id=eq.${encodeURIComponent(id)}&select=*&limit=1`))?.[0];if(!t||!visibleThread(t,ctx)){const e=new Error('Inbox thread not found.');e.status=404;throw e}return t}
async function saveBlockRule(scope,value,ctx,reason='Blocked from Namdar email inbox'){const normalized=scope==='sender'?normalizeEmail(value):domainOf(`x@${String(value||'').replace(/^@/,'')}`);if(!normalized){const e=new Error('Could not determine a valid sender or domain.');e.status=400;throw e}const now=new Date().toISOString();const rows=await db(`support_inbox_blocklist?on_conflict=scope,value`,{method:'POST',prefer:'resolution=merge-duplicates,return=representation',body:{scope,value:normalized,reason:String(reason||'').slice(0,500)||null,active:true,created_by:ctx.user.id,updated_at:now}});return rows?.[0]||null}
async function quarantineExistingDomain(domain,now){const rows=await db('support_inbox_threads?status=neq.spam&select=id,customer_email&limit=500').catch(()=>[]);const matches=(rows||[]).filter(x=>domainOf(x.customer_email)===domain);for(const x of matches)await db(`support_inbox_threads?id=eq.${encodeURIComponent(x.id)}`,{method:'PATCH',body:{status:'spam',unread_count:0,spam_score:100,spam_source:'blocked_domain',spam_reason:`Domain @${domain} is blocked`,updated_at:now}}).catch(()=>null);return matches.length}
module.exports=async function(req,res){try{
  const ctx=await context(req);if(!canInbox(ctx)&&!ctx.isAdmin)return json(res,403,{ok:false,error:'You do not have inbox access.'});
  if(req.method==='GET'){
    if(String(queryParam(req,'blocklist',''))==='1'){if(!ctx.isAdmin)return json(res,403,{ok:false,error:'Only administrators can manage the inbox blocklist.'});const rules=await db('support_inbox_blocklist?active=eq.true&select=id,scope,value,reason,created_by,created_at,updated_at&order=scope.asc,value.asc&limit=500');return json(res,200,{ok:true,rules:rules||[]})}
    const threadId=String(queryParam(req,'threadId','')||'').trim();if(threadId){const t=await getThread(threadId,ctx),messages=await db(`support_inbox_messages?thread_id=eq.${encodeURIComponent(t.id)}&select=id,direction,resend_email_id,email_message_id,in_reply_to,from_email,to_emails,cc_emails,subject,body_text,attachments,sent_by,delivery_status,sent_at,created_at&order=sent_at.asc&limit=300`);if(t.status!=='spam')await db(`support_inbox_threads?id=eq.${encodeURIComponent(t.id)}`,{method:'PATCH',body:{unread_count:0,updated_at:new Date().toISOString()}}).catch(()=>null);return json(res,200,{ok:true,thread:{...t,unread_count:0},messages:messages||[]})}
    const rows=await db('support_inbox_threads?select=*&order=last_message_at.desc&limit=200'),threads=(rows||[]).filter(t=>visibleThread(t,ctx));let enrichedThreads=threads;if(threads.length){const ids=threads.map(t=>t.id).filter(Boolean).slice(0,200),recent=ids.length?await db(`support_inbox_messages?thread_id=in.(${ids.map(x=>encodeURIComponent(x)).join(',')})&select=thread_id,direction,body_text,sent_at,created_at&order=sent_at.desc&limit=500`).catch(()=>[]):[],latest={};for(const m of recent||[])if(m.thread_id&&!latest[m.thread_id])latest[m.thread_id]=m;enrichedThreads=threads.map(t=>{const m=latest[t.id]||{};return{...t,last_message_preview:String(m.body_text||'').slice(0,220),last_direction:m.direction||null}})}let staff=[];if(ctx.isAdmin||ctx.perms?.staff){const profiles=await db('profiles?role=in.(admin,staff)&account_status=eq.active&select=id,full_name,email,role&order=full_name.asc').catch(()=>[]),ids=(profiles||[]).filter(p=>p.role==='staff').map(p=>p.id),access=ids.length?await db(`staff_access?user_id=in.(${ids.map(x=>encodeURIComponent(x)).join(',')})&select=user_id,permissions,active`).catch(()=>[]):[],am=Object.fromEntries((access||[]).map(a=>[a.user_id,a]));staff=(profiles||[]).filter(p=>p.role==='admin'||am[p.id]?.active).map(p=>({...p,permissions:p.role==='admin'?{all:true}:(am[p.id]?.permissions||{})}))}return json(res,200,{ok:true,threads:enrichedThreads,unreadCount:threads.filter(t=>t.status!=='spam').reduce((a,t)=>a+Number(t.unread_count||0),0),staff});
  }
  if(req.method==='POST'){
    const b=parseBody(req),action=String(b.action||'reply');if(action!=='reply')return json(res,400,{ok:false,error:'Unknown inbox action.'});const t=await getThread(String(b.threadId||''),ctx);if(t.status==='spam')return json(res,400,{ok:false,error:'Restore this conversation from Spam before replying.'});const message=String(b.message||'').trim().slice(0,10000);if(!message)return json(res,400,{ok:false,error:'Write a reply first.'});const latest=(await db(`support_inbox_messages?thread_id=eq.${encodeURIComponent(t.id)}&email_message_id=not.is.null&select=email_message_id&order=sent_at.desc&limit=1`))?.[0];const headers=latest?.email_message_id?{'In-Reply-To':latest.email_message_id,'References':latest.email_message_id}:null,subject=/^re:/i.test(t.subject)?t.subject:`Re: ${t.subject}`;const sent=await sendEmail({to:t.customer_email,subject,text:message,from:fromFor(t.mailbox),replyTo:inboundReply(t),headers,archiveForCustomer:!!t.customer_id,customerId:t.customer_id||null,messageCategory:'support',targetPath:'/account?tab=support'});if(!sent?.ok)return json(res,502,{ok:false,error:'The reply could not be sent. Please try again.'});await db('support_inbox_messages',{method:'POST',body:{thread_id:t.id,direction:'outbound',resend_email_id:sent.data?.id||null,email_message_id:null,in_reply_to:latest?.email_message_id||null,from_email:fromFor(t.mailbox),to_emails:[t.customer_email],cc_emails:[],subject,body_text:message,attachments:[],headers:headers||{},sent_by:ctx.user.id,delivery_status:'sent',sent_at:new Date().toISOString()}});await db(`support_inbox_threads?id=eq.${encodeURIComponent(t.id)}`,{method:'PATCH',body:{status:'awaiting_customer',unread_count:0,last_message_at:new Date().toISOString(),updated_at:new Date().toISOString()}});await auditLog(req,ctx,{action:'inbox.reply',entityType:'support_inbox_thread',entityId:t.id,summary:`Replied to ${t.mailbox} inbox thread`,metadata:{customerEmail:t.customer_email,messageLength:message.length}});return json(res,200,{ok:true});
  }
  if(req.method==='PATCH'){
    const b=parseBody(req),action=String(b.action||'read'),now=new Date().toISOString();if(action==='unblock_rule'){if(!ctx.isAdmin)return json(res,403,{ok:false,error:'Only administrators can change the inbox blocklist.'});const rule=(await db(`support_inbox_blocklist?id=eq.${encodeURIComponent(String(b.ruleId||''))}&active=eq.true&select=*&limit=1`))?.[0];if(!rule)return json(res,404,{ok:false,error:'Block rule not found.'});await db(`support_inbox_blocklist?id=eq.${encodeURIComponent(rule.id)}`,{method:'PATCH',body:{active:false,updated_at:now}});await auditLog(req,ctx,{action:'inbox.unblock',entityType:'support_inbox_blocklist',entityId:rule.id,summary:`Unblocked inbox ${rule.scope}`,before:rule,after:{...rule,active:false,updated_at:now}});return json(res,200,{ok:true})}
    const t=await getThread(String(b.threadId||''),ctx),patch={updated_at:now};if(action==='read')patch.unread_count=0;else if(action==='unread')patch.unread_count=t.status==='spam'?0:Math.max(1,Number(t.unread_count||0));else if(action==='assign'){const id=b.userId?String(b.userId):null;if(id){const p=(await db(`profiles?id=eq.${encodeURIComponent(id)}&role=in.(admin,staff)&select=id,role&limit=1`))?.[0];if(!p)return json(res,400,{ok:false,error:'Choose a valid team member.'});if(p.role!=='admin'){const a=(await db(`staff_access?user_id=eq.${encodeURIComponent(id)}&select=permissions,active&limit=1`))?.[0];if(!a?.active||a.permissions?.[t.permission_key||'inbox']!==true)return json(res,400,{ok:false,error:'That team member does not have access to this mailbox.'})}}patch.assigned_to=id}else if(action==='priority'){if(!['low','normal','high','urgent'].includes(b.priority))return json(res,400,{ok:false,error:'Invalid priority.'});patch.priority=b.priority}else if(action==='status'){if(!['awaiting_staff','awaiting_customer','closed','spam'].includes(b.status))return json(res,400,{ok:false,error:'Invalid status.'});patch.status=b.status;if(['closed','spam'].includes(b.status))patch.unread_count=0;if(b.status==='spam'){patch.spam_score=100;patch.spam_source='manual';patch.spam_reason='Marked as spam by Namdar staff'}else if(t.status==='spam'){patch.spam_score=0;patch.spam_source=null;patch.spam_reason=null}}
    else if(action==='spam'){patch.status='spam';patch.unread_count=0;patch.spam_score=100;patch.spam_source='manual';patch.spam_reason=String(b.reason||'Marked as spam by Namdar staff').slice(0,500)}
    else if(action==='phishing'){patch.status='spam';patch.unread_count=0;patch.spam_score=100;patch.spam_source='security';patch.spam_reason=String(b.reason||'Reported as phishing or dangerous mail by Namdar staff').slice(0,500);patch.priority='urgent'}
    else if(action==='not_spam'){patch.status='awaiting_staff';patch.unread_count=0;patch.spam_score=0;patch.spam_source=null;patch.spam_reason=null}
    else if(action==='block_sender'||action==='block_domain'){if(!ctx.isAdmin)return json(res,403,{ok:false,error:'Only administrators can block email senders or domains.'});const scope=action==='block_sender'?'sender':'domain',value=scope==='sender'?normalizeEmail(t.customer_email):domainOf(t.customer_email);if(!value)return json(res,400,{ok:false,error:'Could not determine a valid sender or domain.'});if(scope==='domain'&&PROTECTED_SHARED_DOMAINS.has(value))return json(res,400,{ok:false,error:'This is a shared/public email domain. Block the exact sender instead so legitimate customers are not affected.'});const rule=await saveBlockRule(scope,value,ctx,scope==='sender'?`Blocked sender ${value}`:`Blocked domain @${value}`);patch.status='spam';patch.unread_count=0;patch.spam_score=100;patch.spam_source=scope==='sender'?'blocked_sender':'blocked_domain';patch.spam_reason=scope==='sender'?`Sender ${value} is blocked`:`Domain @${value} is blocked`;if(scope==='sender')await db(`support_inbox_threads?customer_email=eq.${encodeURIComponent(value)}&status=neq.spam`,{method:'PATCH',body:{status:'spam',unread_count:0,spam_score:100,spam_source:'blocked_sender',spam_reason:`Sender ${value} is blocked`,updated_at:now}}).catch(()=>null);else await quarantineExistingDomain(value,now);await auditLog(req,ctx,{action:`inbox.${action}`,entityType:'support_inbox_blocklist',entityId:rule?.id||t.id,summary:`Blocked inbox ${scope}`,metadata:{scope,value}})}
    else return json(res,400,{ok:false,error:'Unknown inbox action.'});await db(`support_inbox_threads?id=eq.${encodeURIComponent(t.id)}`,{method:'PATCH',body:patch});if(action==='assign'&&patch.assigned_to)await createStaffNotification({type:'inbox_assignment',title:'Inbox conversation assigned to you',body:`${t.customer_name||t.customer_email} · ${t.subject}`,targetPath:`/admin?tab=inbox&thread=${encodeURIComponent(t.id)}`,permissionKey:t.permission_key||'inbox',targetUserId:patch.assigned_to,entityType:'support_inbox_thread',entityId:t.id,priority:t.priority||'normal',dedupeKey:`inbox-assigned:${t.id}:${patch.assigned_to}`});await auditLog(req,ctx,{action:`inbox.${action}`,entityType:'support_inbox_thread',entityId:t.id,summary:`Updated ${t.mailbox} inbox thread`,before:t,after:{...t,...patch}});return json(res,200,{ok:true});
  }
  return json(res,405,{ok:false,error:'Method not allowed'});
}catch(e){return safeError(res,e)}};
